version: '3.7'

services:

  wordle_tool_frontend:
    container_name: frontend_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/opt/wordle_tool_frontend'
      - '/opt/wordle_tool_frontend/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true