version: "2"

services:
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    volumes:
      - './:/opt/wordle_tool_backend/' 
    ports:
      - "5000:5000"
   
